[database]
url = "postgres://postgres:postgres@localhost:5432/docport-dev?sslmode=disable"

[server]
host = "localhost:8080"
bind = "0.0.0.0"
port = "8080"

[storage]
provider = "filesystem"
path = "/app/data/storage"
