[server]
host = "localhost:8080"
bind = "0.0.0.0"
port = "8080"

[database]
dsn = "postgres://postgres:postgres@localhost:5432/docport-dev?sslmode=disable"

[auth]
jwksUrl = ""
scopes = [] # Add required token scopes here. Leave empty if you don't want to validate scopes.

[storage]
provider = "filesystem"
path = "/app/data/storage"
