[database]
driver = "sqlite"
url = "file:/app/data/docport.db?_pragma=foreign_keys(ON)"

[server]
host = "localhost:8080"
bind = "127.0.0.1"
port = "8080"

[storage]
provider = "filesystem"
path = "/app/data/storage"
