[server]
host = "localhost:8080"
bind = "0.0.0.0"
port = "8080"

[database]
dsn = "postgres://postgres:postgres@localhost:5432/docport-dev?sslmode=disable"

[auth]
issuer = ""
clientId = ""
clientSecret = ""

[storage]
provider = "filesystem"
path = "/app/data/storage"
